language: python


env:
    global:
        - PYMAIN=3.6.3
        - MAKE_COVER=[ $TRAVIS_PYTHON_VERSION == 3.6.3 ]
        - RELEASE=[[ $TRAVIS_BRANCH == 'release'] && [ $TRAVIS_PYTHON_VERSION == $PYMAIN ]]

python:
  - 3.5.4
  - $PYMAIN

install:
  - ci/install.sh

addons:
  postgresql: "9.4"

before_script:
  - psql -U postgres -f tests/db.sql

script:
  - make test
  - if [[ MAKE_COVER ]]; then make coverage; fi

after_success:
  - if [ $TRAVIS_PYTHON_VERSION == $PYMAIN ]; then codecov; fi
  - if [ $RELEASE ]; then ci/release.sh; fi

notifications:
  email: false
