language: python

python:
  - 3.5.4
  - 3.6.3

install:
  - ci/install.sh

addons:
  postgresql: "9.4"

before_script:
  - psql -U postgres -f tests/db.sql

script:
  - make test
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6.3 ]]; then make coverage; fi

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6.3 ]]; then codecov; fi

notifications:
  email: false
